baseURL = "https://nfrazier.bitbucket.io/"
languageCode = "en-us"
title = "Nick Frazier"
theme = "pristine" 
canonifyURLs = false
enableEmoji = true
googleAnalytics = "UA-100475877-1"

[params]
    portrait = "img/nfrazier.png"
    favicon = "/images/nf-favicon.ico"

[[menu.main]]
  identifier = "blog"
  name = "Home"
  url = "/"
  weight = -100

[[menu.main]]
	name = "Research"
	url = "/research"
	weight = -50

[[menu.main]]
	name = "CV"
	url = "/nfrazier_cv.pdf"
	weight = -25

[[menu.main]]
    name = "contact me"
    url = "mailto:npfrazier@gmail.com"
    weight = -2

[[params.social]]
    title = "Email"
    url = "mailto:npfrazier@gmail.com"
[[params.social]]
    title = "Github"
    url = "https://github.com/npfrazier"
